name: "Environment Setup"
description: "Sets up Python, just, uv, etc."

inputs:
  python_version:
    type: string
    description: "Python version to install"
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y just

    - name: Check out code
      uses: actions/checkout@v3
