name: Continuous Integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run environment setup composite action
        uses: ./.github/actions/environment-setup
        with:
          python _version: "3.12"

      - name: Install project dependencies
        run: just install

      - name: Test
        run: just test

      - name: Lint
        run: just lint

      - name: Type check
        run: just type-check
