name: Continuous Integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Run environment setup composite action
        uses: ./.github/actions/environment-setup

      - name: Lint
        run: just lint

      - name: Test
        run: just test

      - name: Install project dependencies
        run: just install
